### ISSUE TITLE
Import failed?

### ISSUE THREAD

**Issue by Channel3902** [diontimmer/ComfyUI-Vextra-Nodes#7]
![image](https://github.com/diontimmer/ComfyUI-Vextra-Nodes/assets/136620541/23252643-9317-4abe-a2f3-5bdcda9d189c)

**Comment by jeffyspoke** [comment]
I have this issue also

**Comment by iloveuav** [comment]
I have this issue also
![image](https://github.com/diontimmer/ComfyUI-Vextra-Nodes/assets/48607989/349c2701-2666-4b25-b545-d2dc97053f55)

**Comment by may2xxxx** [comment]
I have this issue also

**Comment by hyh813** [comment]
me too ... ...

**Comment by aegis72** [comment]
Same, now.

**Comment by mortael** [comment]
How to fix: manually clone distilgpt2 :)

- open cmd
- go to ComfyUI\custom_nodes\ComfyUI-Vextra-Nodes folder
- make a binary folder (`mkdir binary` under windows)
- run `git clone https://huggingface.co/FredZhang7/distilgpt2-stable-diffusion-v2`
- start ComfyUI

done 👍

**Comment by imminentarchon** [comment]
> How to fix: manually clone distilgpt2 :)
> 
> * open cmd
> * go to ComfyUI\custom_nodes\ComfyUI-Vextra-Nodes folder
> * make a binary folder (`mkdir binary` under windows)
> * run `git clone https://huggingface.co/FredZhang7/distilgpt2-stable-diffusion-v2`
> * start ComfyUI
> 
> done 👍

Still getting the same error even after following these steps unfortunately

**Comment by imminentarchon** [comment]
I guess my issue had to do with issue #11 - no audio device. I deleted the DT_Play_Sound_At_Execution.py node and it loaded correctly.

**Comment by a-niess** [comment]
> How to fix: manually clone distilgpt2 :)
> 
> * open cmd
> * go to ComfyUI\custom_nodes\ComfyUI-Vextra-Nodes folder
> * make a binary folder (`mkdir binary` under windows)
> * run `git clone https://huggingface.co/FredZhang7/distilgpt2-stable-diffusion-v2`
> * start ComfyUI
> 
> done 👍

This does not work for me. @mortael are you suggesting running `git clone https://huggingface.co/FredZhang7/distilgpt2-stable-diffusion-v2` within the `binary` folder? Can you explain why this should work? Thanks so much.

**Comment by zwh3308** [comment]
Same, now.

**Comment by JustinRoper** [comment]
On windows using the comfyui desktop beta, if you are getting this error `Cannot import ComfyUI\custom_nodes/ComfyUI-Vextra-Nodes module for custom nodes: No module named 'custom_nodes.ComfyUI-Vextra-Nodes'` like I was I have a fix for you:
I was able to get it to load / import by:
* going into `ComfyUI\custom_nodes\ComfyUI-Vextra-Nodes\`
* edit `__init__.py`
* replace  `node_import = importlib.import_module('custom_nodes.ComfyUI-Vextra-Nodes.nodes.' + node)`
  * with `node_import = importlib.import_module('ComfyUI-Vextra-Nodes.nodes.' + node)`
